export { default as CartItem } from './CartItem'
export { default as Contact } from './Contact'
export { default as Footer } from './Footer'
export { default as Header } from './Header'
export { default as PopUp } from './PopUp'
export { default as Section } from './Section'
export { default as ShopItem } from './ShopItem'
